import { TRaitngItem } from "../hooks/useGetRaitingList";

export const RAITINGLIST:TRaitngItem[]=[
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
    {
        accent_color_id: 1,
        active_usernames: ['1'],
        bio:'',
        coins: 12,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:12,
        max_reaction_count:3,
        referrerId:  null  ,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
    },
   
]