import { TFrens } from "../types/frensItem";
import frens_ava from '@shared/Frens/assets/frens_img/frens_ava.svg'

export const FRENSLIST:TFrens[]=[
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User',
    },
    {
        avaUrl:frens_ava,
        fren_point: 10000,
        frenReward:100,
        name: 'User_last',
    },
]