import { TFrensItem } from "../hooks/useGetFrensInfo";
import frens_ava from '@shared/Frens/assets/frens_img/frens_ava.svg'

export const FRENSLIST:TFrensItem[]=[
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
    {   accent_color_id: 1,
        active_usernames: [''],
        bio:'',
        coins: 1,
        createdAt:'string',
        first_name:'string',
        last_name:'string',
        id:1,
        max_reaction_count:1,
        referrerId: null,
        role:'string',
        telegramId:'string',
        type:'string',
        updatedAt:'string',
        username:'string',
        day_revenues: 2,
        photo: frens_ava,
    },
]