import {TFrensItem} from "@shared/Frens/hooks/useGetFrensInfo.ts";

export const FRENSLIST:TFrensItem[]=[
  {
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },{
    accent_color_id: 1,
    active_usernames: ["asd"],
    bio:'',
    coins: 10,
    createdAt:'2021-12-12',
    color:'#fff',
    first_name:'Денис',
    last_name:'Байханов',
    id:12,
    max_reaction_count:12,
    referrerId: null,
    role:'',
    telegramId:'1231212',
    type:'qweq',
    updatedAt:'qwe',
    username:'qweqw',
    day_revenues: 1
  },
]