// import fire_ico from '@shared/Tasks/assets/tasks_img/tasksFire.svg'
// import facebook_ico from '@shared/Tasks/assets/tasks_img/facebook_ico.svg'
// import inst_ico from '@shared/Tasks/assets/tasks_img/inst_ico.svg'
import { TTaskItem } from "../hooks/useGetTasksInf";


export const TASKLIST:TTaskItem[]=[
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'adsadsada',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'asdfasd',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'asdasd',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },
    {
        channel_id:'',
       coins:100,
       createdAt:'',
       description:'',
       id:1,
       link:'',
       main_task_id:1,
       status:'pending',
       sub_tasks:[],
       title:'',
       updatedAt:'',

    },

]